# Generated by Django 4.1.13 on 2026-07-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='otp_sent',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='verified',
        ),
    ]
